# -*- coding: utf-8 -*-
"""Jornada faixa preta.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1USCNpoPpkXtCr_nZVD6KX9szQ0JZPq8u
"""

texto = 'facção do rato'
for vez in range (100):
  print(texto)